#!/usr/bin/env python3
"""secrets.local -> .env (без вывода секретов)."""

from __future__ import annotations

import os
import sys
from pathlib import Path

RUNTIME = Path(__file__).resolve().parents[1]
if str(RUNTIME) not in sys.path:
    sys.path.insert(0, str(RUNTIME))

SECRETS = RUNTIME / "secrets.local"
EXAMPLE = RUNTIME / "secrets.local.example"
ENV_TARGET = RUNTIME / ".env"

DEFAULTS = {
    "TMKI_OCR_MODE": "http",
    "OPENAI_MODEL": "gpt-4o-mini",
    "MINERU_API_URL": "https://mineru.net/api/v4",
    "MISTRAL_OCR_API_URL": "https://api.mistral.ai/v1/ocr",
    "MISTRAL_OCR_MODEL": "mistral-ocr-latest",
    "TMKI_ARM_KS_ARCHIVE": r"D:\Курсор\Армировка КС",
    "TMKI_REGULATIONS_ARCHIVE": r"D:\Курсор\СКРУ-2",
    "TMKI_STT_PROVIDER": "whisper",
    "WHISPER_PRESET": "fast",
    "WHISPER_DEVICE": "cpu",
    "WHISPER_COMPUTE_TYPE": "int8",
    "TMKI_LLM_PROVIDER": "ollama",
    "TMKI_RAG_FUSION": "1",
    "TMKI_CROSS_ENCODER_RERANK": "1",
    "TMKI_QUALITY_RERANK": "1",
    "TMKI_INCREMENTAL_INGEST": "1",
    "TMKI_INGEST_PARSER": "auto",
    "TMKI_RAG_FUSION_LLM": "auto",
    "TMKI_INDEX_BACKEND": "auto",
    "TMKI_CROSS_ENCODER_RERANK": "auto",
}

from tmki_runtime.secrets import is_valid_api_secret, is_valid_openai_api_key


def read_map(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def main() -> int:
    if not SECRETS.is_file() and EXAMPLE.is_file():
        SECRETS.write_text(EXAMPLE.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"CREATED:{SECRETS}")

    secrets = read_map(SECRETS)
    existing = read_map(ENV_TARGET)
    merged = dict(DEFAULTS)
    merged.update({k: v for k, v in existing.items() if v})
    merged.update({k: v for k, v in secrets.items() if v})

    has_openai = is_valid_openai_api_key(merged.get("OPENAI_API_KEY"))
    has_mistral = is_valid_api_secret(merged.get("MISTRAL_API_KEY"))
    has_mineru = is_valid_api_secret(merged.get("MINERU_API_KEY"))

    if has_openai and merged.get("TMKI_LLM_PROVIDER") == "openai":
        merged["TMKI_LLM_PROVIDER"] = "openai"
    elif merged.get("TMKI_LLM_PROVIDER") in ("ollama", "stub"):
        pass
    elif has_openai:
        merged["TMKI_LLM_PROVIDER"] = "ollama"
    else:
        merged["TMKI_LLM_PROVIDER"] = "ollama"
        merged.pop("OPENAI_API_KEY", None)
    if not has_mistral:
        merged.pop("MISTRAL_API_KEY", None)
    if not has_mineru:
        merged.pop("MINERU_API_KEY", None)

    if has_mistral or has_mineru:
        merged["TMKI_OCR_MODE"] = "http"
    else:
        merged["TMKI_OCR_MODE"] = "local"

    locked = set(secrets.keys())
    from tmki_runtime.env_autoconfigure import autoconfigure, apply_autoconfigure_to_secrets

    auto_updates, auto_log = autoconfigure(merged, locked_keys=locked)
    merged.update(auto_updates)
    if os.environ.get("TMKI_AUTO_SYNC_SECRETS", "1").strip().lower() not in ("0", "false", "no"):
        auto_log.extend(apply_autoconfigure_to_secrets(SECRETS, locked_keys=locked))

    missing = []
    if not has_openai:
        missing.append("OPENAI_API_KEY")
    if not has_mistral:
        missing.append("MISTRAL_API_KEY")
    if not has_mineru:
        missing.append("MINERU_API_KEY")
    if missing:
        print("WARN:missing=" + ",".join(missing))

    lines = [
        "# generated by merge_env.py",
        "# source: secrets.local",
        "",
    ]
    for k in sorted(merged):
        lines.append(f"{k}={merged[k]}")
    ENV_TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"WROTE:{ENV_TARGET}")
    print(f"TMKI_OCR_MODE={merged['TMKI_OCR_MODE']}")
    print(f"TMKI_LLM_PROVIDER={merged['TMKI_LLM_PROVIDER']}")
    for line in auto_log:
        if line.startswith("AUTO:"):
            print(line)
    if "TMKI_INGEST_PARSER" in merged:
        print(f"TMKI_INGEST_PARSER={merged['TMKI_INGEST_PARSER']}")
    if merged.get("TMKI_INDEX_BACKEND") == "pgvector":
        print(f"TMKI_INDEX_BACKEND=pgvector")
    if merged.get("TMKI_RAG_FUSION_LLM") == "1":
        print("TMKI_RAG_FUSION_LLM=1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
